### ISSUE TITLE
Extraer la cantidad de votos con los que los congresistas fueron electos

### ISSUE THREAD

**Issue by jeqo** [GolpistasPe/congreso-golpista-data#11]
Posible fuente: resultadoshistorico.onpe.gob.pe/PRECE2020/

**Comment by jjacostupa** [comment]
Hola, a qué se refieren con cantidad de datos? Cantidad de votos?

**Comment by jeqo** [comment]
@jjacostupa si! ya corregi el titulo, gracias!

**Comment by jjacostupa** [comment]
Hice un fork con código y datos, pero para todos los postulantes al congreso. Estaría bueno si lo pudieran revisar.

Fork: https://github.com/jjacostupa/congreso-golpista-data

Fuente:
 http://resultadoshistorico.onpe.gob.pe/PRECE2020/EleccionesCongresales/Revc/D40021

**Comment by jeqo** [comment]
@jjacostupa podrias crear un pull request para revisarlo? me avisas si necesitas ayuda. gracias!

**Comment by jjacostupa** [comment]
@jeqo puedes revisar #13

**Comment by jeqo** [comment]
Solucionado por #13, gracias @jjacostupa !
